version: '3'

services:

  discovery-server:
    image: damiangor/city-info-app:discovery-server
    networks:
      - mynetwork
    ports:
      - 8761:8761
      
  spring-cloud-config-server:
    image: damiangor/city-info-app:spring-cloud-config-server
    environment:
      - JAVA_OPTS=
         -DDISCOVERY_SERVER=http://discovery-server:8761/eureka
    depends_on:
      - discovery-server
    networks:
      - mynetwork      
    ports:
      - 8888:8888 
      
  db:
    image: mysql:8.0.18
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: oauthdb
    networks:
      - mynetwork        
    ports:
        - 3308:3306 
    cap_add:
        - SYS_PTRACE
    security_opt:
        - seccomp:unconfined
        
  authorization-server:
    image: damiangor/city-info-app:authorization-server
    environment:
      - JAVA_OPTS=
        -DDISCOVERY_SERVER=http://discovery-server:8761/eureka
    networks:
      - mynetwork
    restart: on-failure
    depends_on:
      - discovery-server
      - db
    ports:
      - 9292:9292        
      
  city-info-service:
    image: damiangor/city-info-app:city-info-service
    environment:
      - JAVA_OPTS=
        -DDISCOVERY_SERVER=http://discovery-server:8761/eureka
    restart: on-failure
    depends_on:
      - discovery-server
      - spring-cloud-config-server
    networks:
      - mynetwork
    ports:
      - 8081:8081  

  gateway-server:
    image: damiangor/city-info-app:gateway-server
    environment:
      - JAVA_OPTS=
        -DDISCOVERY_SERVER=http://discovery-server:8761/eureka
    restart: on-failure
    depends_on:
      - discovery-server
      - spring-cloud-config-server
    networks:
      - mynetwork
    ports:
      - 8080:8080
      
  country-info-service:
    image: damiangor/city-info-app:country-info-service
    environment:
      - JAVA_OPTS=
        -DDISCOVERY_SERVER=http://discovery-server:8761/eureka
    restart: on-failure
    depends_on:
      - discovery-server
      - spring-cloud-config-server
    networks:
      - mynetwork
    ports:
      - 8083:8083
      
  weather-info-service:
    image: damiangor/city-info-app:weather-info-service
    environment:
      - JAVA_OPTS=
        -DDISCOVERY_SERVER=http://discovery-server:8761/eureka
    restart: on-failure
    depends_on:
      - discovery-server
      - spring-cloud-config-server
    networks:
      - mynetwork
    ports:
      - 8082:8082      

networks:
  mynetwork: